version: "3.8"

services:
  app:
    build: .
    restart: always
    environment:
      TZ: Europe/Moscow
      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
      ECOMRU_BITRIX_URL: ${ECOMRU_BITRIX_URL}

    command: sh script.sh
    volumes:
      - /home/get/logs_all//bitrix24_parser/:/app/logs/
    


    
